//
//  ChemistryElements.swift
//  ElementQuiz
//
//  Created by Balmes Pavlov on 11/12/18.
//  Copyright © 2018 Balmes Pavlov. All rights reserved.
//

import UIKit

struct ChemistryElements {
    let atomicNumber: Int
    let backgroundColor: UIColor
    let elementName: String
    let symbol: String
    let atomicMass: Double
    let numOfNeutrons: Int
    let numOfProtons: Int
    let numOfElectrons: Int
    let period: Int
    let group: Int?
    let phase: String
    let radioactive: Bool?
    let natural: Bool?
    let metal: Bool?
    let nonmetal: Bool?
    let metalloid: Bool?
    let type: String?
    let atomicRadius: Float?
    let electronegativity: Float?
    let firstIonization: Float?
    let density: Double?
    let meltingPoint: Float?
    let boilingPoint: Float?
    let numOfIsotopes: Int?
    let discoverer: String?
    let Year: Int?
    let specificHeat: Float?
    let NumberofShells: Int
    let NumberofValence: Int?
    
//    AtomicNumber
//    BackgroundColor
//    Element
//    Symbol
//    AtomicMass
//    NumberofNeutrons
//    NumberofProtons
//    NumberofElectrons
//    Period
//    Group
//    Phase
//    Radioactive
//    Natural
//    Metal
//    Nonmetal
//    Metalloid
//    Type
//    AtomicRadius
//    Electronegativity
//    FirstIonization
//    Density
//    MeltingPoint
//    BoilingPoint
//    NumberOfIsotopes
//    Discoverer
//    Year
//    SpecificHeat
//    NumberofShells
//    NumberofValence
    
}

var colorDict: [String: UIColor] = [
    "alkaliMetal":               UIColor(red: 255/255, green: 102/255, blue: 102/255, alpha: 1.0),
    "reactiveNonmetal":          UIColor(red: 240/255, green: 255/255, blue: 143/255, alpha: 1.0),
    "nobleGas":                  UIColor(red: 192/255, green: 255/255, blue: 255/255, alpha: 1.0),
    "alkalineEarthMetal":        UIColor(red: 255/255, green: 222/255, blue: 173/255, alpha: 1.0),
    "metalloid":                 UIColor(red: 204/255, green: 204/255, blue: 153/255, alpha: 1.0),
    "postTransitionalMetal":     UIColor(red: 204/255, green: 204/255, blue: 20/255, alpha: 1.0),
    "transitionMetal":           UIColor(red: 255/255, green: 192/255, blue: 192/255, alpha: 1.0),
    "lanthanide":                UIColor(red: 255/255, green: 191/255, blue: 255/255, alpha: 1.0),
    "actinide":                  UIColor(red: 255/255, green: 153/255, blue: 204/255, alpha: 1.0),
    "unknownChemicalProperties": UIColor(red: 232/255, green: 232/255, blue: 232/255, alpha: 1.0)
]

let elements: [ChemistryElements] = [
    ChemistryElements(atomicNumber: 1, backgroundColor: colorDict["reactiveNonmetal"]!, elementName: "Hydrogen", symbol: "H", atomicMass: 1.007, numOfNeutrons: 0, numOfProtons: 1, numOfElectrons: 1, period: 1, group: 1, phase: "gas", radioactive: nil, natural: true, metal: nil, nonmetal: true, metalloid: nil, type: "yes", atomicRadius: 0.79, electronegativity: 2.2, firstIonization: 13.5984, density: 0.0000899, meltingPoint: 14.175, boilingPoint: 20.28, numOfIsotopes: 3, discoverer: "Cavendish", Year: 1766, specificHeat: 14.304, NumberofShells: 1, NumberofValence: 1),
    ChemistryElements(atomicNumber: 2, backgroundColor: colorDict["nobleGas"]!, elementName: "Helium", symbol: "He", atomicMass: 4.002, numOfNeutrons: 2, numOfProtons: 2, numOfElectrons: 2, period: 1, group: 18, phase: "gas", radioactive: nil, natural: true, metal: nil, nonmetal: true, metalloid: nil, type: "yes", atomicRadius: 0.49, electronegativity: nil, firstIonization: 24.5874, density: 0.000179, meltingPoint: nil, boilingPoint: 4.22, numOfIsotopes: 5, discoverer: "Janssen", Year: 1868, specificHeat: 5.193, NumberofShells: 1, NumberofValence: nil),
    ChemistryElements(atomicNumber: 3, backgroundColor: colorDict["alkaliMetal"]!, elementName: "Lithium", symbol: "Li", atomicMass: 6.941, numOfNeutrons: 4, numOfProtons: 3, numOfElectrons: 3, period: 2, group: 1, phase: "solid", radioactive: nil, natural: true, metal: true, nonmetal: nil, metalloid: nil, type: "yes", atomicRadius: 2.1, electronegativity: 0.98, firstIonization: 5.3917, density: 0.534, meltingPoint: 453.85, boilingPoint: 1615, numOfIsotopes: 5, discoverer: "Arfvedson", Year: 1817, specificHeat: 3.582, NumberofShells: 2, NumberofValence: 1),
    ChemistryElements(atomicNumber: 4, backgroundColor: colorDict["alkalineEarthMetal"]!, elementName: "Beryllium", symbol: "Be", atomicMass: 9.012, numOfNeutrons: 5, numOfProtons: 4, numOfElectrons: 4, period: 2, group: 2, phase: "solid", radioactive: nil, natural: true, metal: true, nonmetal: nil, metalloid: nil, type: "yes", atomicRadius: 1.4, electronegativity: 1.57, firstIonization: 9.3227, density: 1.85, meltingPoint: 1560.15, boilingPoint: 2742, numOfIsotopes: 6, discoverer: "Vaulquelin", Year: 1798, specificHeat: 1.825, NumberofShells: 2, NumberofValence: 2),
    ChemistryElements(atomicNumber: 5, backgroundColor: colorDict["metalloid"]!, elementName: "Boron", symbol: "B", atomicMass: 10.811, numOfNeutrons: 6, numOfProtons: 5, numOfElectrons: 5, period: 2, group: 13, phase: "solid", radioactive: nil, natural: true, metal: nil, nonmetal: nil, metalloid: true, type: "yes", atomicRadius: 1.2, electronegativity: 2.04, firstIonization: 8.298, density: 2.34, meltingPoint: 2573.15, boilingPoint: 4200, numOfIsotopes: 6, discoverer: "Gay-Lussac", Year: 1808, specificHeat: 1.026, NumberofShells: 2, NumberofValence: 3),
    ChemistryElements(atomicNumber: 6, backgroundColor: colorDict["reactiveNonmetal"]!, elementName: "Carbon", symbol: "C", atomicMass: 12.011, numOfNeutrons: 6, numOfProtons: 6, numOfElectrons: 6, period: 2, group: 14, phase: "solid", radioactive: nil, natural: true, metal: nil, nonmetal: true, metalloid: nil, type: "yes", atomicRadius: 0.91, electronegativity: 2.55, firstIonization: 11.2603, density: 2.27, meltingPoint: 3948.15, boilingPoint: 4300, numOfIsotopes: 7, discoverer: "Prehistoric", Year: nil, specificHeat: 0.709, NumberofShells: 2, NumberofValence: 4),
    ChemistryElements(atomicNumber: 7, backgroundColor: colorDict["reactiveNonmetal"]!, elementName: "Nitrogen", symbol: "N", atomicMass: 14.007, numOfNeutrons: 7, numOfProtons: 7, numOfElectrons: 7, period: 2, group: 15, phase: "gas", radioactive: nil, natural: true, metal: nil, nonmetal: true, metalloid: nil, type: "yes", atomicRadius: 0.75, electronegativity: 3.04, firstIonization: 14.5341, density: 0.00125, meltingPoint: 63.29, boilingPoint: 77.36, numOfIsotopes: 8, discoverer: "Rutherford", Year: 1772, specificHeat: 1.04, NumberofShells: 2, NumberofValence: 5),
    ChemistryElements(atomicNumber: 8, backgroundColor: colorDict["reactiveNonmetal"]!, elementName: "Oxygen", symbol: "O", atomicMass: 15.999, numOfNeutrons: 8, numOfProtons: 8, numOfElectrons: 8, period: 2, group: 16, phase: "gas", radioactive: nil, natural: true, metal: nil, nonmetal: true, metalloid: nil, type: "yes", atomicRadius: 0.65, electronegativity: 3.44, firstIonization: 13.6181, density: 0.00143, meltingPoint: 50.5, boilingPoint: 90.2, numOfIsotopes: 8, discoverer: "Priestley/Scheele", Year: 1774, specificHeat: 0.918, NumberofShells: 2, NumberofValence: 6),
    ChemistryElements(atomicNumber: 9, backgroundColor: colorDict["reactiveNonmetal"]!, elementName: "Fluorine", symbol: "F", atomicMass: 18.998, numOfNeutrons: 10, numOfProtons: 9, numOfElectrons: 9, period: 2, group: 17, phase: "gas", radioactive: nil, natural: true, metal: nil, nonmetal: true, metalloid: nil, type: "yes", atomicRadius: 0.57, electronegativity: 3.98, firstIonization: 17.4228, density: 0.0017, meltingPoint: 53.63, boilingPoint: 85.03, numOfIsotopes: 6, discoverer: "Moissan", Year: 1886, specificHeat: 0.824, NumberofShells: 2, NumberofValence: 7),
    ChemistryElements(atomicNumber: 10, backgroundColor: colorDict["nobleGas"]!, elementName: "Neon", symbol: "Ne", atomicMass: 20.18, numOfNeutrons: 10, numOfProtons: 10, numOfElectrons: 10, period: 2, group: 18, phase: "gas", radioactive: nil, natural: true, metal: nil, nonmetal: true, metalloid: nil, type: "yes", atomicRadius: 0.51, electronegativity: nil, firstIonization: 21.5645, density: 0.0009, meltingPoint: 24.703, boilingPoint: 27.07, numOfIsotopes: 8, discoverer: "Ramsay and Travers", Year: 1898, specificHeat: 1.03, NumberofShells: 2, NumberofValence: 8),
    ChemistryElements(atomicNumber: 11, backgroundColor: colorDict["alkaliMetal"]!, elementName: "Sodium", symbol: "Na", atomicMass: 22.99, numOfNeutrons: 12, numOfProtons: 11, numOfElectrons: 11, period: 3, group: 1, phase: "solid", radioactive: nil, natural: true, metal: true, nonmetal: nil, metalloid: nil, type: "yes", atomicRadius: 2.2, electronegativity: 0.93, firstIonization: 5.1391, density: 0.971, meltingPoint: 371.15, boilingPoint: 1156, numOfIsotopes: 7, discoverer: "Davy", Year: 1807, specificHeat: 1.228, NumberofShells: 3, NumberofValence: 1),
    ChemistryElements(atomicNumber: 12, backgroundColor: colorDict["alkalineEarthMetal"]!, elementName: "Magnesium", symbol: "Mg", atomicMass: 24.305, numOfNeutrons: 12, numOfProtons: 12, numOfElectrons: 12, period: 3, group: 2, phase: "solid", radioactive: nil, natural: true, metal: true, nonmetal: nil, metalloid: nil, type: "yes", atomicRadius: 1.7, electronegativity: 1.31, firstIonization: 7.6462, density: 1.74, meltingPoint: 923.15, boilingPoint: 1363, numOfIsotopes: 8, discoverer: "Black", Year: 1755, specificHeat: 1.023, NumberofShells: 3, NumberofValence: 2),
    ChemistryElements(atomicNumber: 13, backgroundColor: colorDict["postTransitionalMetal"]!, elementName: "Aluminum", symbol: "Al", atomicMass: 26.982, numOfNeutrons: 14, numOfProtons: 13, numOfElectrons: 13, period: 3, group: 13, phase: "solid", radioactive: nil, natural: true, metal: true, nonmetal: nil, metalloid: nil, type: "yes", atomicRadius: 1.8, electronegativity: 1.61, firstIonization: 5.9858, density: 2.7, meltingPoint: 933.4, boilingPoint: 2792, numOfIsotopes: 8, discoverer: "Wshler", Year: 1827, specificHeat: 0.897, NumberofShells: 3, NumberofValence: 3),
    ChemistryElements(atomicNumber: 14, backgroundColor: colorDict["metalloid"]!, elementName: "Silicon", symbol: "Si", atomicMass: 28.086, numOfNeutrons: 14, numOfProtons: 14, numOfElectrons: 14, period: 3, group: 14, phase: "solid", radioactive: nil, natural: true, metal: nil, nonmetal: nil, metalloid: true, type: "yes", atomicRadius: 1.5, electronegativity: 1.9, firstIonization: 8.1517, density: 2.33, meltingPoint: 1683.15, boilingPoint: 3538, numOfIsotopes: 8, discoverer: "Berzelius", Year: 1824, specificHeat: 0.705, NumberofShells: 3, NumberofValence: 4),
    ChemistryElements(atomicNumber: 15, backgroundColor: colorDict["reactiveNonmetal"]!, elementName: "Phosphorus", symbol: "P", atomicMass: 30.974, numOfNeutrons: 16, numOfProtons: 15, numOfElectrons: 15, period: 3, group: 15, phase: "solid", radioactive: nil, natural: true, metal: nil, nonmetal: true, metalloid: nil, type: "yes", atomicRadius: 1.2, electronegativity: 2.19, firstIonization: 10.4867, density: 1.82, meltingPoint: 317.25, boilingPoint: 553, numOfIsotopes: 7, discoverer: "BranBrand", Year: 1669, specificHeat: 0.769, NumberofShells: 3, NumberofValence: 5),
    ChemistryElements(atomicNumber: 16, backgroundColor: colorDict["reactiveNonmetal"]!, elementName: "Sulfur", symbol: "S", atomicMass: 32.065, numOfNeutrons: 16, numOfProtons: 16, numOfElectrons: 16, period: 3, group: 16, phase: "solid", radioactive: nil, natural: true, metal: nil, nonmetal: true, metalloid: nil, type: "yes", atomicRadius: 1.1, electronegativity: 2.58, firstIonization: 10.36, density: 2.07, meltingPoint: 388.51, boilingPoint: 717.8, numOfIsotopes: 10, discoverer: "Prehistoric", Year: nil, specificHeat: 0.71, NumberofShells: 3, NumberofValence: 6),
    ChemistryElements(atomicNumber: 17, backgroundColor: colorDict["reactiveNonmetal"]!, elementName: "Chlorine", symbol: "Cl", atomicMass: 35.453, numOfNeutrons: 18, numOfProtons: 17, numOfElectrons: 17, period: 3, group: 17, phase: "gas", radioactive: nil, natural: true, metal: nil, nonmetal: true, metalloid: nil, type: "yes", atomicRadius: 0.97, electronegativity: 3.16, firstIonization: 12.9676, density: 0.00321, meltingPoint: 172.31, boilingPoint: 239.11, numOfIsotopes: 11, discoverer: "Scheele", Year: 1774, specificHeat: 0.479, NumberofShells: 3, NumberofValence: 7),
    ChemistryElements(atomicNumber: 18, backgroundColor: colorDict["nobleGas"]!, elementName: "Argon", symbol: "Ar", atomicMass: 39.948, numOfNeutrons: 22, numOfProtons: 18, numOfElectrons: 18, period: 3, group: 18, phase: "gas", radioactive: nil, natural: true, metal: nil, nonmetal: true, metalloid: nil, type: "yes", atomicRadius: 0.88, electronegativity: nil, firstIonization: 15.7596, density: 0.00178, meltingPoint: 83.96, boilingPoint: 87.3, numOfIsotopes: 8, discoverer: "Rayleigh and Ramsay", Year: 1894, specificHeat: 0.52, NumberofShells: 3, NumberofValence: 8),
    ChemistryElements(atomicNumber: 19, backgroundColor: colorDict["alkaliMetal"]!, elementName: "Potassium", symbol: "K", atomicMass: 39.098, numOfNeutrons: 20, numOfProtons: 19, numOfElectrons: 19, period: 4, group: 1, phase: "solid", radioactive: nil, natural: true, metal: true, nonmetal: nil, metalloid: nil, type: "yes", atomicRadius: 2.8, electronegativity: 0.82, firstIonization: 4.3407, density: 0.862, meltingPoint: 336.5, boilingPoint: 1032, numOfIsotopes: 10, discoverer: "Davy", Year: 1807, specificHeat: 0.757, NumberofShells: 4, NumberofValence: 1),
    ChemistryElements(atomicNumber: 20, backgroundColor: colorDict["alkalineEarthMetal"]!, elementName: "Calcium", symbol: "Ca", atomicMass: 40.078, numOfNeutrons: 20, numOfProtons: 20, numOfElectrons: 20, period: 4, group: 2, phase: "solid", radioactive: nil, natural: true, metal: true, nonmetal: nil, metalloid: nil, type: "yes", atomicRadius: 2.2, electronegativity: 1, firstIonization: 6.1132, density: 1.54, meltingPoint: 1112.15, boilingPoint: 1757, numOfIsotopes: 14, discoverer: "Davy", Year: 1808, specificHeat: 0.647, NumberofShells: 4, NumberofValence: 2),
    ChemistryElements(atomicNumber: 21, backgroundColor: colorDict["transitionMetal"]!, elementName: "Scandium", symbol: "Sc", atomicMass: 44.956, numOfNeutrons: 24, numOfProtons: 21, numOfElectrons: 21, period: 4, group: 3, phase: "solid", radioactive: nil, natural: true, metal: true, nonmetal: nil, metalloid: nil, type: "yes", atomicRadius: 2.1, electronegativity: 1.36, firstIonization: 6.5615, density: 2.99, meltingPoint: 1812.15, boilingPoint: 3109, numOfIsotopes: 15, discoverer: "Nilson", Year: 1878, specificHeat: 0.568, NumberofShells: 4, NumberofValence: nil),
    ChemistryElements(atomicNumber: 22, backgroundColor: colorDict["transitionMetal"]!, elementName: "Titanium", symbol: "Ti", atomicMass: 47.867, numOfNeutrons: 26, numOfProtons: 22, numOfElectrons: 22, period: 4, group: 4, phase: "solid", radioactive: nil, natural: true, metal: true, nonmetal: nil, metalloid: nil, type: "yes", atomicRadius: 2, electronegativity: 1.54, firstIonization: 6.8281, density: 4.54, meltingPoint: 1933.15, boilingPoint: 3560, numOfIsotopes: 9, discoverer: "Gregor", Year: 1791, specificHeat: 0.523, NumberofShells: 4, NumberofValence: nil),
    ChemistryElements(atomicNumber: 23, backgroundColor: colorDict["transitionMetal"]!, elementName: "Vanadium", symbol: "V", atomicMass: 50.942, numOfNeutrons: 28, numOfProtons: 23, numOfElectrons: 23, period: 4, group: 5, phase: "solid", radioactive: nil, natural: true, metal: true, nonmetal: nil, metalloid: nil, type: "yes", atomicRadius: 1.9, electronegativity: 1.63, firstIonization: 6.7462, density: 6.11, meltingPoint: 2175.15, boilingPoint: 3680, numOfIsotopes: 9, discoverer: "   del Rio", Year: 1801, specificHeat: 0.489, NumberofShells: 4, NumberofValence: nil),
    ChemistryElements(atomicNumber: 24, backgroundColor: colorDict["transitionMetal"]!, elementName: "Chromium", symbol: "Cr", atomicMass: 51.996, numOfNeutrons: 28, numOfProtons: 24, numOfElectrons: 24, period: 4, group: 6, phase: "solid", radioactive: nil, natural: true, metal: true, nonmetal: nil, metalloid: nil, type: "yes", atomicRadius: 1.9, electronegativity: 1.66, firstIonization: 6.7665, density: 7.15, meltingPoint: 2130.15, boilingPoint: 2944, numOfIsotopes: 9, discoverer: "Vauquelin", Year: 1797, specificHeat: 0.449, NumberofShells: 4, NumberofValence: nil),
    ChemistryElements(atomicNumber: 25, backgroundColor: colorDict["transitionMetal"]!, elementName: "Manganese", symbol: "Mn", atomicMass: 54.938, numOfNeutrons: 30, numOfProtons: 25, numOfElectrons: 25, period: 4, group: 7, phase: "solid", radioactive: nil, natural: true, metal: true, nonmetal: nil, metalloid: nil, type: "yes", atomicRadius: 1.8, electronegativity: 1.55, firstIonization: 7.434, density: 7.44, meltingPoint: 1519.15, boilingPoint: 2334, numOfIsotopes: 11, discoverer: "Gahn, Scheele", Year: 1774, specificHeat: 0.479, NumberofShells: 4, NumberofValence: nil),
    ChemistryElements(atomicNumber: 26, backgroundColor: colorDict["transitionMetal"]!, elementName: "Iron", symbol: "Fe", atomicMass: 55.845, numOfNeutrons: 30, numOfProtons: 26, numOfElectrons: 26, period: 4, group: 8, phase: "solid", radioactive: nil, natural: true, metal: true, nonmetal: nil, metalloid: nil, type: "yes", atomicRadius: 1.7, electronegativity: 1.83, firstIonization: 7.9024, density: 7.87, meltingPoint: 1808.15, boilingPoint: 3134, numOfIsotopes: 10, discoverer: "Prehistoric", Year: nil, specificHeat: 0.449, NumberofShells: 4, NumberofValence: nil),
    ChemistryElements(atomicNumber: 27, backgroundColor: colorDict["transitionMetal"]!, elementName: "Cobalt", symbol: "Co", atomicMass: 58.933, numOfNeutrons: 32, numOfProtons: 27, numOfElectrons: 27, period: 4, group: 9, phase: "solid", radioactive: nil, natural: true, metal: true, nonmetal: nil, metalloid: nil, type: "yes", atomicRadius: 1.7, electronegativity: 1.88, firstIonization: 7.881, density: 8.86, meltingPoint: 1768.15, boilingPoint: 3200, numOfIsotopes: 14, discoverer: "Brandt", Year: 1735, specificHeat: 0.421, NumberofShells: 4, NumberofValence: nil),
    ChemistryElements(atomicNumber: 28, backgroundColor: colorDict["transitionMetal"]!, elementName: "Nickel", symbol: "Ni", atomicMass: 58.693, numOfNeutrons: 31, numOfProtons: 28, numOfElectrons: 28, period: 4, group: 10, phase: "solid", radioactive: nil, natural: true, metal: true, nonmetal: nil, metalloid: nil, type: "yes", atomicRadius: 1.6, electronegativity: 1.91, firstIonization: 7.6398, density: 8.91, meltingPoint: 1726.15, boilingPoint: 3186, numOfIsotopes: 11, discoverer: "Cronstedt", Year: 1751, specificHeat: 0.444, NumberofShells: 4, NumberofValence: nil),
    ChemistryElements(atomicNumber: 29, backgroundColor: colorDict["transitionMetal"]!, elementName: "Copper", symbol: "Cu", atomicMass: 63.546, numOfNeutrons: 35, numOfProtons: 29, numOfElectrons: 29, period: 4, group: 11, phase: "solid", radioactive: nil, natural: true, metal: true, nonmetal: nil, metalloid: nil, type: "yes", atomicRadius: 1.6, electronegativity: 1.9, firstIonization: 7.7264, density: 8.96, meltingPoint: 1357.75, boilingPoint: 2835, numOfIsotopes: 11, discoverer: "Prehistoric", Year: nil, specificHeat: 0.385, NumberofShells: 4, NumberofValence: nil),
    ChemistryElements(atomicNumber: 30, backgroundColor: colorDict["postTransitionalMetal"]!, elementName: "Zinc", symbol: "Zn", atomicMass: 65.38, numOfNeutrons: 35, numOfProtons: 30, numOfElectrons: 30, period: 4, group: 12, phase: "solid", radioactive: nil, natural: true, metal: true, nonmetal: nil, metalloid: nil, type: "yes", atomicRadius: 1.5, electronegativity: 1.65, firstIonization: 9.3942, density: 7.13, meltingPoint: 692.88, boilingPoint: 1180, numOfIsotopes: 15, discoverer: "Prehistoric", Year: nil, specificHeat: 0.388, NumberofShells: 4, NumberofValence: nil),
    ChemistryElements(atomicNumber: 31, backgroundColor: colorDict["postTransitionalMetal"]!, elementName: "Gallium", symbol: "Ga", atomicMass: 69.723, numOfNeutrons: 39, numOfProtons: 31, numOfElectrons: 31, period: 4, group: 13, phase: "solid", radioactive: nil, natural: true, metal: true, nonmetal: nil, metalloid: nil, type: "yes", atomicRadius: 1.8, electronegativity: 1.81, firstIonization: 5.9993, density: 5.91, meltingPoint: 302.91, boilingPoint: 2477, numOfIsotopes: 14, discoverer: "de Boisbaudran", Year: 1875, specificHeat: 0.371, NumberofShells: 4, NumberofValence: 3),
    ChemistryElements(atomicNumber: 32, backgroundColor: colorDict["metalloid"]!, elementName: "Germanium", symbol: "Ge", atomicMass: 72.64, numOfNeutrons: 41, numOfProtons: 32, numOfElectrons: 32, period: 4, group: 14, phase: "solid", radioactive: nil, natural: true, metal: nil, nonmetal: nil, metalloid: true, type: "yes", atomicRadius: 1.5, electronegativity: 2.01, firstIonization: 7.8994, density: 5.32, meltingPoint: 1211.45, boilingPoint: 3106, numOfIsotopes: 17, discoverer: "Winkler", Year: 1886, specificHeat: 0.32, NumberofShells: 4, NumberofValence: 4),
    ChemistryElements(atomicNumber: 33, backgroundColor: colorDict["metalloid"]!, elementName: "Arsenic", symbol: "As", atomicMass: 74.922, numOfNeutrons: 42, numOfProtons: 33, numOfElectrons: 33, period: 4, group: 15, phase: "solid", radioactive: nil, natural: true, metal: nil, nonmetal: nil, metalloid: true, type: "yes", atomicRadius: 1.3, electronegativity: 2.18, firstIonization: 9.7886, density: 5.78, meltingPoint: 1090.15, boilingPoint: 887, numOfIsotopes: 14, discoverer: "Albertus Magnus", Year: 1250, specificHeat: 0.329, NumberofShells: 4, NumberofValence: 5),
    ChemistryElements(atomicNumber: 34, backgroundColor: colorDict["reactiveNonmetal"]!, elementName: "Selenium", symbol: "Se", atomicMass: 78.96, numOfNeutrons: 45, numOfProtons: 34, numOfElectrons: 34, period: 4, group: 16, phase: "solid", radioactive: nil, natural: true, metal: nil, nonmetal: true, metalloid: nil, type: "yes", atomicRadius: 1.2, electronegativity: 2.55, firstIonization: 9.7524, density: 4.81, meltingPoint: 494.15, boilingPoint: 958, numOfIsotopes: 20, discoverer: "Berzelius", Year: 1817, specificHeat: 0.321, NumberofShells: 4, NumberofValence: 6),
    ChemistryElements(atomicNumber: 35, backgroundColor: colorDict["reactiveNonmetal"]!, elementName: "Bromine", symbol: "Br", atomicMass: 79.904, numOfNeutrons: 45, numOfProtons: 35, numOfElectrons: 35, period: 4, group: 17, phase: "liq", radioactive: nil, natural: true, metal: nil, nonmetal: true, metalloid: nil, type: "yes", atomicRadius: 1.1, electronegativity: 2.96, firstIonization: 11.8138, density: 3.12, meltingPoint: 266.05, boilingPoint: 332, numOfIsotopes: 19, discoverer: "Balard", Year: 1826, specificHeat: 0.474, NumberofShells: 4, NumberofValence: 7),
    ChemistryElements(atomicNumber: 36, backgroundColor: colorDict["nobleGas"]!, elementName: "Krypton", symbol: "Kr", atomicMass: 83.798, numOfNeutrons: 48, numOfProtons: 36, numOfElectrons: 36, period: 4, group: 18, phase: "gas", radioactive: nil, natural: true, metal: nil, nonmetal: true, metalloid: nil, type: "yes", atomicRadius: 1, electronegativity: nil, firstIonization: 13.9996, density: 0.00373, meltingPoint: 115.93, boilingPoint: 119.93, numOfIsotopes: 23, discoverer: "Ramsay and Travers", Year: 1898, specificHeat: 0.248, NumberofShells: 4, NumberofValence: 8),
    ChemistryElements(atomicNumber: 37, backgroundColor: colorDict["alkaliMetal"]!, elementName: "Rubidium", symbol: "Rb", atomicMass: 85.468, numOfNeutrons: 48, numOfProtons: 37, numOfElectrons: 37, period: 5, group: 1, phase: "solid", radioactive: nil, natural: true, metal: true, nonmetal: nil, metalloid: nil, type: "yes", atomicRadius: 3, electronegativity: 0.82, firstIonization: 4.1771, density: 1.53, meltingPoint: 312.79, boilingPoint: 961, numOfIsotopes: 20, discoverer: "Bunsen and Kirchoff", Year: 1861, specificHeat: 0.363, NumberofShells: 5, NumberofValence: 1),
    ChemistryElements(atomicNumber: 38, backgroundColor: colorDict["alkalineEarthMetal"]!, elementName: "Strontium", symbol: "Sr", atomicMass: 87.62, numOfNeutrons: 50, numOfProtons: 38, numOfElectrons: 38, period: 5, group: 2, phase: "solid", radioactive: nil, natural: true, metal: true, nonmetal: nil, metalloid: nil, type: "yes", atomicRadius: 2.5, electronegativity: 0.95, firstIonization: 5.6949, density: 2.64, meltingPoint: 1042.15, boilingPoint: 1655, numOfIsotopes: 18, discoverer: "Davy", Year: 1808, specificHeat: 0.301, NumberofShells: 5, NumberofValence: 2),
    ChemistryElements(atomicNumber: 39, backgroundColor: colorDict["transitionMetal"]!, elementName: "Yttrium", symbol: "Y", atomicMass: 88.906, numOfNeutrons: 50, numOfProtons: 39, numOfElectrons: 39, period: 5, group: 3, phase: "solid", radioactive: nil, natural: true, metal: true, nonmetal: nil, metalloid: nil, type: "yes", atomicRadius: 2.3, electronegativity: 1.22, firstIonization: 6.2173, density: 4.47, meltingPoint: 1799.15, boilingPoint: 3609, numOfIsotopes: 21, discoverer: "Gadolin", Year: 1794, specificHeat: 0.298, NumberofShells: 5, NumberofValence: nil),
    ChemistryElements(atomicNumber: 40, backgroundColor: colorDict["transitionMetal"]!, elementName: "Zirconium", symbol: "Zr", atomicMass: 91.224, numOfNeutrons: 51, numOfProtons: 40, numOfElectrons: 40, period: 5, group: 4, phase: "solid", radioactive: nil, natural: true, metal: true, nonmetal: nil, metalloid: nil, type: "yes", atomicRadius: 2.2, electronegativity: 1.33, firstIonization: 6.6339, density: 6.51, meltingPoint: 2125.15, boilingPoint: 4682, numOfIsotopes: 20, discoverer: "Klaproth", Year: 1789, specificHeat: 0.278, NumberofShells: 5, NumberofValence: nil),
    ChemistryElements(atomicNumber: 41, backgroundColor: colorDict["transitionMetal"]!, elementName: "Niobium", symbol: "Nb", atomicMass: 92.906, numOfNeutrons: 52, numOfProtons: 41, numOfElectrons: 41, period: 5, group: 5, phase: "solid", radioactive: nil, natural: true, metal: true, nonmetal: nil, metalloid: nil, type: "yes", atomicRadius: 2.1, electronegativity: 1.6, firstIonization: 6.7589, density: 8.57, meltingPoint: 2741.15, boilingPoint: 5017, numOfIsotopes: 24, discoverer: "Hatchett", Year: 1801, specificHeat: 0.265, NumberofShells: 5, NumberofValence: nil),
    ChemistryElements(atomicNumber: 42, backgroundColor: colorDict["transitionMetal"]!, elementName: "Molybdenum", symbol: "Mo", atomicMass: 95.96, numOfNeutrons: 54, numOfProtons: 42, numOfElectrons: 42, period: 5, group: 6, phase: "solid", radioactive: nil, natural: true, metal: true, nonmetal: nil, metalloid: nil, type: "yes", atomicRadius: 2, electronegativity: 2.16, firstIonization: 7.0924, density: 10.2, meltingPoint: 2890.15, boilingPoint: 4912, numOfIsotopes: 20, discoverer: "Scheele", Year: 1778, specificHeat: 0.251, NumberofShells: 5, NumberofValence: nil),
    ChemistryElements(atomicNumber: 43, backgroundColor: colorDict["transitionMetal"]!, elementName: "Technetium", symbol: "Tc", atomicMass: 98, numOfNeutrons: 55, numOfProtons: 43, numOfElectrons: 43, period: 5, group: 7, phase: "artificial", radioactive: true, natural: nil, metal: true, nonmetal: nil, metalloid: nil, type: nil, atomicRadius: 2, electronegativity: 1.9, firstIonization: 7.28, density: 11.5, meltingPoint: 2473.15, boilingPoint: 5150, numOfIsotopes: 23, discoverer: "Perrier and SegrÔøΩ", Year: 1937, specificHeat: nil, NumberofShells: 5, NumberofValence: nil),
    ChemistryElements(atomicNumber: 44, backgroundColor: colorDict["transitionMetal"]!, elementName: "Ruthenium", symbol: "Ru", atomicMass: 101.07, numOfNeutrons: 57, numOfProtons: 44, numOfElectrons: 44, period: 5, group: 8, phase: "solid", radioactive: nil, natural: true, metal: true, nonmetal: nil, metalloid: nil, type: "yes", atomicRadius: 1.9, electronegativity: 2.2, firstIonization: 7.3605, density: 12.4, meltingPoint: 2523.15, boilingPoint: 4423, numOfIsotopes: 16, discoverer: "Klaus", Year: 1844, specificHeat: 0.238, NumberofShells: 5, NumberofValence: nil),
    ChemistryElements(atomicNumber: 45, backgroundColor: colorDict["transitionMetal"]!, elementName: "Rhodium", symbol: "Rh", atomicMass: 102.906, numOfNeutrons: 58, numOfProtons: 45, numOfElectrons: 45, period: 5, group: 9, phase: "solid", radioactive: nil, natural: true, metal: true, nonmetal: nil, metalloid: nil, type: "yes", atomicRadius: 1.8, electronegativity: 2.28, firstIonization: 7.4589, density: 12.4, meltingPoint: 2239.15, boilingPoint: 3968, numOfIsotopes: 20, discoverer: "Wollaston", Year: 1803, specificHeat: 0.243, NumberofShells: 5, NumberofValence: nil),
    ChemistryElements(atomicNumber: 46, backgroundColor: colorDict["transitionMetal"]!, elementName: "Palladium", symbol: "Pd", atomicMass: 106.42, numOfNeutrons: 60, numOfProtons: 46, numOfElectrons: 46, period: 5, group: 10, phase: "solid", radioactive: nil, natural: true, metal: true, nonmetal: nil, metalloid: nil, type: "yes", atomicRadius: 1.8, electronegativity: 2.2, firstIonization: 8.3369, density: 12, meltingPoint: 1825.15, boilingPoint: 3236, numOfIsotopes: 21, discoverer: "Wollaston", Year: 1803, specificHeat: 0.244, NumberofShells: 5, NumberofValence: nil),
    ChemistryElements(atomicNumber: 47, backgroundColor: colorDict["transitionMetal"]!, elementName: "Silver", symbol: "Ag", atomicMass: 107.868, numOfNeutrons: 61, numOfProtons: 47, numOfElectrons: 47, period: 5, group: 11, phase: "solid", radioactive: nil, natural: true, metal: true, nonmetal: nil, metalloid: nil, type: "yes", atomicRadius: 1.8, electronegativity: 1.93, firstIonization: 7.5762, density: 10.5, meltingPoint: 1234.15, boilingPoint: 2435, numOfIsotopes: 27, discoverer: "Prehistoric", Year: nil, specificHeat: 0.235, NumberofShells: 5, NumberofValence: nil),
    ChemistryElements(atomicNumber: 48, backgroundColor: colorDict["postTransitionalMetal"]!, elementName: "Cadmium", symbol: "Cd", atomicMass: 112.411, numOfNeutrons: 64, numOfProtons: 48, numOfElectrons: 48, period: 5, group: 12, phase: "solid", radioactive: nil, natural: true, metal: true, nonmetal: nil, metalloid: nil, type: "yes", atomicRadius: 1.7, electronegativity: 1.69, firstIonization: 8.9938, density: 8.69, meltingPoint: 594.33, boilingPoint: 1040, numOfIsotopes: 22, discoverer: "Stromeyer", Year: 1817, specificHeat: 0.232, NumberofShells: 5, NumberofValence: nil),
    ChemistryElements(atomicNumber: 49, backgroundColor: colorDict["postTransitionalMetal"]!, elementName: "Indium", symbol: "In", atomicMass: 114.818, numOfNeutrons: 66, numOfProtons: 49, numOfElectrons: 49, period: 5, group: 13, phase: "solid", radioactive: nil, natural: true, metal: true, nonmetal: nil, metalloid: nil, type: "yes", atomicRadius: 2, electronegativity: 1.78, firstIonization: 5.7864, density: 7.31, meltingPoint: 429.91, boilingPoint: 2345, numOfIsotopes: 34, discoverer: "Reich and Richter", Year: 1863, specificHeat: 0.233, NumberofShells: 5, NumberofValence: 3),
    ChemistryElements(atomicNumber: 50, backgroundColor: colorDict["postTransitionalMetal"]!, elementName: "Tin", symbol: "Sn", atomicMass: 118.71, numOfNeutrons: 69, numOfProtons: 50, numOfElectrons: 50, period: 5, group: 14, phase: "solid", radioactive: nil, natural: true, metal: true, nonmetal: nil, metalloid: nil, type: "yes", atomicRadius: 1.7, electronegativity: 1.96, firstIonization: 7.3439, density: 7.29, meltingPoint: 505.21, boilingPoint: 2875, numOfIsotopes: 28, discoverer: "Prehistoric", Year: nil, specificHeat: 0.228, NumberofShells: 5, NumberofValence: 4),
    ChemistryElements(atomicNumber: 51, backgroundColor: colorDict["metalloid"]!, elementName: "Antimony", symbol: "Sb", atomicMass: 121.76, numOfNeutrons: 71, numOfProtons: 51, numOfElectrons: 51, period: 5, group: 15, phase: "solid", radioactive: nil, natural: true, metal: nil, nonmetal: nil, metalloid: true, type: "yes", atomicRadius: 1.5, electronegativity: 2.05, firstIonization: 8.6084, density: 6.69, meltingPoint: 904.05, boilingPoint: 1860, numOfIsotopes: 29, discoverer: "Early historic times", Year: nil, specificHeat: 0.207, NumberofShells: 5, NumberofValence: 5),
    ChemistryElements(atomicNumber: 52, backgroundColor: colorDict["metalloid"]!, elementName: "Tellurium", symbol: "Te", atomicMass: 127.6, numOfNeutrons: 76, numOfProtons: 52, numOfElectrons: 52, period: 5, group: 16, phase: "solid", radioactive: nil, natural: true, metal: nil, nonmetal: nil, metalloid: true, type: "yes", atomicRadius: 1.4, electronegativity: 2.1, firstIonization: 9.0096, density: 6.23, meltingPoint: 722.8, boilingPoint: 1261, numOfIsotopes: 29, discoverer: "von Reichenstein", Year: 1782, specificHeat: 0.202, NumberofShells: 5, NumberofValence: 6),
    ChemistryElements(atomicNumber: 53, backgroundColor: colorDict["reactiveNonmetal"]!, elementName: "Iodine", symbol: "I", atomicMass: 126.904, numOfNeutrons: 74, numOfProtons: 53, numOfElectrons: 53, period: 5, group: 17, phase: "solid", radioactive: nil, natural: true, metal: nil, nonmetal: true, metalloid: nil, type: "yes", atomicRadius: 1.3, electronegativity: 2.66, firstIonization: 10.4513, density: 4.93, meltingPoint: 386.65, boilingPoint: 457.4, numOfIsotopes: 24, discoverer: "Courtois", Year: 1811, specificHeat: 0.214, NumberofShells: 5, NumberofValence: 7),
    ChemistryElements(atomicNumber: 54, backgroundColor: colorDict["nobleGas"]!, elementName: "Xenon", symbol: "Xe", atomicMass: 131.293, numOfNeutrons: 77, numOfProtons: 54, numOfElectrons: 54, period: 5, group: 18, phase: "gas", radioactive: nil, natural: true, metal: nil, nonmetal: true, metalloid: nil, type: "yes", atomicRadius: 1.2, electronegativity: nil, firstIonization: 12.1298, density: 0.00589, meltingPoint: 161.45, boilingPoint: 165.03, numOfIsotopes: 31, discoverer: "Ramsay and Travers", Year: 1898, specificHeat: 0.158, NumberofShells: 5, NumberofValence: 8),
    ChemistryElements(atomicNumber: 55, backgroundColor: colorDict["alkaliMetal"]!, elementName: "Cesium", symbol: "Cs", atomicMass: 132.905, numOfNeutrons: 78, numOfProtons: 55, numOfElectrons: 55, period: 6, group: 1, phase: "solid", radioactive: nil, natural: true, metal: true, nonmetal: nil, metalloid: nil, type: "yes", atomicRadius: 3.3, electronegativity: 0.79, firstIonization: 3.8939, density: 1.87, meltingPoint: 301.7, boilingPoint: 944, numOfIsotopes: 22, discoverer: "Bunsen and Kirchoff", Year: 1860, specificHeat: 0.242, NumberofShells: 6, NumberofValence: 1),
    ChemistryElements(atomicNumber: 56, backgroundColor: colorDict["alkalineEarthMetal"]!, elementName: "Barium", symbol: "Ba", atomicMass: 137.327, numOfNeutrons: 81, numOfProtons: 56, numOfElectrons: 56, period: 6, group: 2, phase: "solid", radioactive: nil, natural: true, metal: true, nonmetal: nil, metalloid: nil, type: "yes", atomicRadius: 2.8, electronegativity: 0.89, firstIonization: 5.2117, density: 3.59, meltingPoint: 1002.15, boilingPoint: 2170, numOfIsotopes: 25, discoverer: "Davy", Year: 1808, specificHeat: 0.204, NumberofShells: 6, NumberofValence: 2),
    ChemistryElements(atomicNumber: 57, backgroundColor: colorDict["lanthanide"]!, elementName: "Lanthanum", symbol: "La", atomicMass: 138.905, numOfNeutrons: 82, numOfProtons: 57, numOfElectrons: 57, period: 6, group: 3, phase: "solid", radioactive: nil, natural: true, metal: true, nonmetal: nil, metalloid: nil, type: "yes", atomicRadius: 2.7, electronegativity: 1.1, firstIonization: 5.5769, density: 6.15, meltingPoint: 1193.15, boilingPoint: 3737, numOfIsotopes: 19, discoverer: "Mosander", Year: 1839, specificHeat: 0.195, NumberofShells: 6, NumberofValence: nil),
    ChemistryElements(atomicNumber: 58, backgroundColor: colorDict["lanthanide"]!, elementName: "Cerium", symbol: "Ce", atomicMass: 140.116, numOfNeutrons: 82, numOfProtons: 58, numOfElectrons: 58, period: 6, group: nil, phase: "solid", radioactive: nil, natural: true, metal: true, nonmetal: nil, metalloid: nil, type: "yes", atomicRadius: 2.7, electronegativity: 1.12, firstIonization: 5.5387, density: 6.77, meltingPoint: 1071.15, boilingPoint: 3716, numOfIsotopes: 19, discoverer: "Berzelius", Year: 1803, specificHeat: 0.192, NumberofShells: 6, NumberofValence: nil),
    ChemistryElements(atomicNumber: 59, backgroundColor: colorDict["lanthanide"]!, elementName: "Praseodymium", symbol: "Pr", atomicMass: 140.908, numOfNeutrons: 82, numOfProtons: 59, numOfElectrons: 59, period: 6, group: nil, phase: "solid", radioactive: nil, natural: true, metal: true, nonmetal: nil, metalloid: nil, type: "yes", atomicRadius: 2.7, electronegativity: 1.13, firstIonization: 5.473, density: 6.77, meltingPoint: 1204.15, boilingPoint: 3793, numOfIsotopes: 15, discoverer: "von Welsbach", Year: 1885, specificHeat: 0.193, NumberofShells: 6, NumberofValence: nil),
    ChemistryElements(atomicNumber: 60, backgroundColor: colorDict["lanthanide"]!, elementName: "Neodymium", symbol: "Nd", atomicMass: 144.242, numOfNeutrons: 84, numOfProtons: 60, numOfElectrons: 60, period: 6, group: nil, phase: "solid", radioactive: nil, natural: true, metal: true, nonmetal: nil, metalloid: nil, type: "yes", atomicRadius: 2.6, electronegativity: 1.14, firstIonization: 5.525, density: 7.01, meltingPoint: 1289.15, boilingPoint: 3347, numOfIsotopes: 16, discoverer: "von Welsbach", Year: 1885, specificHeat: 0.19, NumberofShells: 6, NumberofValence: nil),
    ChemistryElements(atomicNumber: 61, backgroundColor: colorDict["lanthanide"]!, elementName: "Promethium", symbol: "Pm", atomicMass: 145, numOfNeutrons: 84, numOfProtons: 61, numOfElectrons: 61, period: 6, group: nil, phase: "artificial", radioactive: true, natural: nil, metal: true, nonmetal: nil, metalloid: nil, type: nil, atomicRadius: 2.6, electronegativity: 1.13, firstIonization: 5.582, density: 7.26, meltingPoint: 1204.15, boilingPoint: 3273, numOfIsotopes: 14, discoverer: "Marinsky et al.", Year: 1945, specificHeat: nil, NumberofShells: 6, NumberofValence: nil),
    ChemistryElements(atomicNumber: 62, backgroundColor: colorDict["lanthanide"]!, elementName: "Samarium", symbol: "Sm", atomicMass: 150.36, numOfNeutrons: 88, numOfProtons: 62, numOfElectrons: 62, period: 6, group: nil, phase: "solid", radioactive: nil, natural: true, metal: true, nonmetal: nil, metalloid: nil, type: "yes", atomicRadius: 2.6, electronegativity: 1.17, firstIonization: 5.6437, density: 7.52, meltingPoint: 1345.15, boilingPoint: 2067, numOfIsotopes: 17, discoverer: "Boisbaudran", Year: 1879, specificHeat: 0.197, NumberofShells: 6, NumberofValence: nil),
    ChemistryElements(atomicNumber: 63, backgroundColor: colorDict["lanthanide"]!, elementName: "Europium", symbol: "Eu", atomicMass: 151.964, numOfNeutrons: 89, numOfProtons: 63, numOfElectrons: 63, period: 6, group: nil, phase: "solid", radioactive: nil, natural: true, metal: true, nonmetal: nil, metalloid: nil, type: "yes", atomicRadius: 2.6, electronegativity: 1.2, firstIonization: 5.6704, density: 5.24, meltingPoint: 1095.15, boilingPoint: 1802, numOfIsotopes: 21, discoverer: "Demarcay", Year: 1901, specificHeat: 0.182, NumberofShells: 6, NumberofValence: nil),
    ChemistryElements(atomicNumber: 64, backgroundColor: colorDict["lanthanide"]!, elementName: "Gadolinium", symbol: "Gd", atomicMass: 157.25, numOfNeutrons: 93, numOfProtons: 64, numOfElectrons: 64, period: 6, group: nil, phase: "solid", radioactive: nil, natural: true, metal: true, nonmetal: nil, metalloid: nil, type: "yes", atomicRadius: 2.5, electronegativity: 1.2, firstIonization: 6.1501, density: 7.9, meltingPoint: 1585.15, boilingPoint: 3546, numOfIsotopes: 17, discoverer: "de Marignac", Year: 1880, specificHeat: 0.236, NumberofShells: 6, NumberofValence: nil),
    ChemistryElements(atomicNumber: 65, backgroundColor: colorDict["lanthanide"]!, elementName: "Terbium", symbol: "Tb", atomicMass: 158.925, numOfNeutrons: 94, numOfProtons: 65, numOfElectrons: 65, period: 6, group: nil, phase: "solid", radioactive: nil, natural: true, metal: true, nonmetal: nil, metalloid: nil, type: "yes", atomicRadius: 2.5, electronegativity: 1.2, firstIonization: 5.8638, density: 8.23, meltingPoint: 1630.15, boilingPoint: 3503, numOfIsotopes: 24, discoverer: "Mosander", Year: 1843, specificHeat: 0.182, NumberofShells: 6, NumberofValence: nil),
    ChemistryElements(atomicNumber: 66, backgroundColor: colorDict["lanthanide"]!, elementName: "Dysprosium", symbol: "Dy", atomicMass: 162.5, numOfNeutrons: 97, numOfProtons: 66, numOfElectrons: 66, period: 6, group: nil, phase: "solid", radioactive: nil, natural: true, metal: true, nonmetal: nil, metalloid: nil, type: "yes", atomicRadius: 2.5, electronegativity: 1.22, firstIonization: 5.9389, density: 8.55, meltingPoint: 1680.15, boilingPoint: 2840, numOfIsotopes: 21, discoverer: "de Boisbaudran", Year: 1886, specificHeat: 0.17, NumberofShells: 6, NumberofValence: nil),
    ChemistryElements(atomicNumber: 67, backgroundColor: colorDict["lanthanide"]!, elementName: "Holmium", symbol: "Ho", atomicMass: 164.93, numOfNeutrons: 98, numOfProtons: 67, numOfElectrons: 67, period: 6, group: nil, phase: "solid", radioactive: nil, natural: true, metal: true, nonmetal: nil, metalloid: nil, type: "yes", atomicRadius: 2.5, electronegativity: 1.23, firstIonization: 6.0215, density: 8.8, meltingPoint: 1743.15, boilingPoint: 2993, numOfIsotopes: 29, discoverer: "Delafontaine and Soret", Year: 1878, specificHeat: 0.165, NumberofShells: 6, NumberofValence: nil),
    ChemistryElements(atomicNumber: 68, backgroundColor: colorDict["lanthanide"]!, elementName: "Erbium", symbol: "Er", atomicMass: 167.259, numOfNeutrons: 99, numOfProtons: 68, numOfElectrons: 68, period: 6, group: nil, phase: "solid", radioactive: nil, natural: true, metal: true, nonmetal: nil, metalloid: nil, type: "yes", atomicRadius: 2.5, electronegativity: 1.24, firstIonization: 6.1077, density: 9.07, meltingPoint: 1795.15, boilingPoint: 3503, numOfIsotopes: 16, discoverer: "Mosander", Year: 1843, specificHeat: 0.168, NumberofShells: 6, NumberofValence: nil),
    ChemistryElements(atomicNumber: 69, backgroundColor: colorDict["lanthanide"]!, elementName: "Thulium", symbol: "Tm", atomicMass: 168.934, numOfNeutrons: 100, numOfProtons: 69, numOfElectrons: 69, period: 6, group: nil, phase: "solid", radioactive: nil, natural: true, metal: true, nonmetal: nil, metalloid: nil, type: "yes", atomicRadius: 2.4, electronegativity: 1.25, firstIonization: 6.1843, density: 9.32, meltingPoint: 1818.15, boilingPoint: 2223, numOfIsotopes: 18, discoverer: "Cleve", Year: 1879, specificHeat: 0.16, NumberofShells: 6, NumberofValence: nil),
    ChemistryElements(atomicNumber: 70, backgroundColor: colorDict["lanthanide"]!, elementName: "Ytterbium", symbol: "Yb", atomicMass: 173.054, numOfNeutrons: 103, numOfProtons: 70, numOfElectrons: 70, period: 6, group: nil, phase: "solid", radioactive: nil, natural: true, metal: true, nonmetal: nil, metalloid: nil, type: "yes", atomicRadius: 2.4, electronegativity: 1.1, firstIonization: 6.2542, density: 6.97, meltingPoint: 1097.15, boilingPoint: 1469, numOfIsotopes: 16, discoverer: "Marignac", Year: 1878, specificHeat: 0.155, NumberofShells: 6, NumberofValence: nil),
    ChemistryElements(atomicNumber: 71, backgroundColor: colorDict["lanthanide"]!, elementName: "Lutetium", symbol: "Lu", atomicMass: 174.967, numOfNeutrons: 104, numOfProtons: 71, numOfElectrons: 71, period: 6, group: nil, phase: "solid", radioactive: nil, natural: true, metal: true, nonmetal: nil, metalloid: nil, type: "yes", atomicRadius: 2.3, electronegativity: 1.27, firstIonization: 5.4259, density: 9.84, meltingPoint: 1936.15, boilingPoint: 3675, numOfIsotopes: 22, discoverer: "Urbain/ von Welsbach", Year: 1907, specificHeat: 0.154, NumberofShells: 6, NumberofValence: nil),
    ChemistryElements(atomicNumber: 72, backgroundColor: colorDict["transitionMetal"]!, elementName: "Hafnium", symbol: "Hf", atomicMass: 178.49, numOfNeutrons: 106, numOfProtons: 72, numOfElectrons: 72, period: 6, group: 4, phase: "solid", radioactive: nil, natural: true, metal: true, nonmetal: nil, metalloid: nil, type: "yes", atomicRadius: 2.2, electronegativity: 1.3, firstIonization: 6.8251, density: 13.3, meltingPoint: 2500.15, boilingPoint: 4876, numOfIsotopes: 17, discoverer: "Coster and von Hevesy", Year: 1923, specificHeat: 0.144, NumberofShells: 6, NumberofValence: nil),
    ChemistryElements(atomicNumber: 73, backgroundColor: colorDict["transitionMetal"]!, elementName: "Tantalum", symbol: "Ta", atomicMass: 180.948, numOfNeutrons: 108, numOfProtons: 73, numOfElectrons: 73, period: 6, group: 5, phase: "solid", radioactive: nil, natural: true, metal: true, nonmetal: nil, metalloid: nil, type: "yes", atomicRadius: 2.1, electronegativity: 1.5, firstIonization: 7.5496, density: 16.7, meltingPoint: 3269.15, boilingPoint: 5731, numOfIsotopes: 19, discoverer: "Ekeberg", Year: 1801, specificHeat: 0.14, NumberofShells: 6, NumberofValence: nil),
    ChemistryElements(atomicNumber: 74, backgroundColor: colorDict["transitionMetal"]!, elementName: "Wolfram", symbol: "W", atomicMass: 183.84, numOfNeutrons: 110, numOfProtons: 74, numOfElectrons: 74, period: 6, group: 6, phase: "solid", radioactive: nil, natural: true, metal: true, nonmetal: nil, metalloid: nil, type: "yes", atomicRadius: 2, electronegativity: 2.36, firstIonization: 7.864, density: 19.3, meltingPoint: 3680.15, boilingPoint: 5828, numOfIsotopes: 22, discoverer: "J. and F. d'Elhuyar", Year: 1783, specificHeat: 0.132, NumberofShells: 6, NumberofValence: nil),
    ChemistryElements(atomicNumber: 75, backgroundColor: colorDict["transitionMetal"]!, elementName: "Rhenium", symbol: "Re", atomicMass: 186.207, numOfNeutrons: 111, numOfProtons: 75, numOfElectrons: 75, period: 6, group: 7, phase: "solid", radioactive: nil, natural: true, metal: true, nonmetal: nil, metalloid: nil, type: "yes", atomicRadius: 2, electronegativity: 1.9, firstIonization: 7.8335, density: 21, meltingPoint: 3453.15, boilingPoint: 5869, numOfIsotopes: 21, discoverer: "Noddack, Berg, and Tacke", Year: 1925, specificHeat: 0.137, NumberofShells: 6, NumberofValence: nil),
    ChemistryElements(atomicNumber: 76, backgroundColor: colorDict["transitionMetal"]!, elementName: "Osmium", symbol: "Os", atomicMass: 190.23, numOfNeutrons: 114, numOfProtons: 76, numOfElectrons: 76, period: 6, group: 8, phase: "solid", radioactive: nil, natural: true, metal: true, nonmetal: nil, metalloid: nil, type: "yes", atomicRadius: 1.9, electronegativity: 2.2, firstIonization: 8.4382, density: 22.6, meltingPoint: 3300.15, boilingPoint: 5285, numOfIsotopes: 19, discoverer: "Tennant", Year: 1803, specificHeat: 0.13, NumberofShells: 6, NumberofValence: nil),
    ChemistryElements(atomicNumber: 77, backgroundColor: colorDict["transitionMetal"]!, elementName: "Iridium", symbol: "Ir", atomicMass: 192.217, numOfNeutrons: 115, numOfProtons: 77, numOfElectrons: 77, period: 6, group: 9, phase: "solid", radioactive: nil, natural: true, metal: true, nonmetal: nil, metalloid: nil, type: "yes", atomicRadius: 1.9, electronegativity: 2.2, firstIonization: 8.967, density: 22.6, meltingPoint: 2716.15, boilingPoint: 4701, numOfIsotopes: 25, discoverer: "Tennant", Year: 1804, specificHeat: 0.131, NumberofShells: 6, NumberofValence: nil),
    ChemistryElements(atomicNumber: 78, backgroundColor: colorDict["transitionMetal"]!, elementName: "Platinum", symbol: "Pt", atomicMass: 195.084, numOfNeutrons: 117, numOfProtons: 78, numOfElectrons: 78, period: 6, group: 10, phase: "solid", radioactive: nil, natural: true, metal: true, nonmetal: nil, metalloid: nil, type: "yes", atomicRadius: 1.8, electronegativity: 2.28, firstIonization: 8.9587, density: 21.5, meltingPoint: 2045.15, boilingPoint: 4098, numOfIsotopes: 32, discoverer: "Ulloa/Wood", Year: 1735, specificHeat: 0.133, NumberofShells: 6, NumberofValence: nil),
    ChemistryElements(atomicNumber: 79, backgroundColor: colorDict["transitionMetal"]!, elementName: "Gold", symbol: "Au", atomicMass: 196.967, numOfNeutrons: 118, numOfProtons: 79, numOfElectrons: 79, period: 6, group: 11, phase: "solid", radioactive: nil, natural: true, metal: true, nonmetal: nil, metalloid: nil, type: "yes", atomicRadius: 1.8, electronegativity: 2.54, firstIonization: 9.2255, density: 19.3, meltingPoint: 1337.73, boilingPoint: 3129, numOfIsotopes: 21, discoverer: "Prehistoric", Year: nil, specificHeat: 0.129, NumberofShells: 6, NumberofValence: nil),
    ChemistryElements(atomicNumber: 80, backgroundColor: colorDict["postTransitionalMetal"]!, elementName: "Mercury", symbol: "Hg", atomicMass: 200.59, numOfNeutrons: 121, numOfProtons: 80, numOfElectrons: 80, period: 6, group: 12, phase: "liq", radioactive: nil, natural: true, metal: true, nonmetal: nil, metalloid: nil, type: "yes", atomicRadius: 1.8, electronegativity: 2, firstIonization: 10.4375, density: 13.5, meltingPoint: 234.43, boilingPoint: 630, numOfIsotopes: 26, discoverer: "Prehistoric", Year: nil, specificHeat: 0.14, NumberofShells: 6, NumberofValence: nil),
    ChemistryElements(atomicNumber: 81, backgroundColor: colorDict["postTransitionalMetal"]!, elementName: "Thallium", symbol: "Tl", atomicMass: 204.383, numOfNeutrons: 123, numOfProtons: 81, numOfElectrons: 81, period: 6, group: 13, phase: "solid", radioactive: nil, natural: true, metal: true, nonmetal: nil, metalloid: nil, type: "yes", atomicRadius: 2.1, electronegativity: 2.04, firstIonization: 6.1082, density: 11.9, meltingPoint: 577.15, boilingPoint: 1746, numOfIsotopes: 28, discoverer: "Crookes", Year: 1861, specificHeat: 0.129, NumberofShells: 6, NumberofValence: 3),
    ChemistryElements(atomicNumber: 82, backgroundColor: colorDict["postTransitionalMetal"]!, elementName: "Lead", symbol: "Pb", atomicMass: 207.2, numOfNeutrons: 125, numOfProtons: 82, numOfElectrons: 82, period: 6, group: 14, phase: "solid", radioactive: nil, natural: true, metal: true, nonmetal: nil, metalloid: nil, type: "yes", atomicRadius: 1.8, electronegativity: 2.33, firstIonization: 7.4167, density: 11.3, meltingPoint: 600.75, boilingPoint: 2022, numOfIsotopes: 29, discoverer: "Prehistoric", Year: nil, specificHeat: 0.129, NumberofShells: 6, NumberofValence: 4),
    ChemistryElements(atomicNumber: 83, backgroundColor: colorDict["postTransitionalMetal"]!, elementName: "Bismuth", symbol: "Bi", atomicMass: 208.98, numOfNeutrons: 126, numOfProtons: 83, numOfElectrons: 83, period: 6, group: 15, phase: "solid", radioactive: nil, natural: true, metal: true, nonmetal: nil, metalloid: nil, type: "yes", atomicRadius: 1.6, electronegativity: 2.02, firstIonization: 7.2856, density: 9.81, meltingPoint: 544.67, boilingPoint: 1837, numOfIsotopes: 19, discoverer: "Geoffroy the Younger", Year: 1753, specificHeat: 0.122, NumberofShells: 6, NumberofValence: 5),
    ChemistryElements(atomicNumber: 84, backgroundColor: colorDict["postTransitionalMetal"]!, elementName: "Polonium", symbol: "Po", atomicMass: 210, numOfNeutrons: 126, numOfProtons: 84, numOfElectrons: 84, period: 6, group: 16, phase: "solid", radioactive: true, natural: true, metal: nil, nonmetal: nil, metalloid: true, type: "yes", atomicRadius: 1.5, electronegativity: 2, firstIonization: 8.417, density: 9.32, meltingPoint: 527.15, boilingPoint: 1235, numOfIsotopes: 34, discoverer: "Curie", Year: 1898, specificHeat: nil, NumberofShells: 6, NumberofValence: 6),
    ChemistryElements(atomicNumber: 85, backgroundColor: colorDict["metalloid"]!, elementName: "Astatine", symbol: "At", atomicMass: 210, numOfNeutrons: 125, numOfProtons: 85, numOfElectrons: 85, period: 6, group: 17, phase: "solid", radioactive: true, natural: true, metal: nil, nonmetal: true, metalloid: nil, type: "yes", atomicRadius: 1.4, electronegativity: 2.2, firstIonization: 9.3, density: 7, meltingPoint: 575.15, boilingPoint: 610, numOfIsotopes: 21, discoverer: "Corson et al.", Year: 1940, specificHeat: nil, NumberofShells: 6, NumberofValence: 7),
    ChemistryElements(atomicNumber: 86, backgroundColor: colorDict["nobleGas"]!, elementName: "Radon", symbol: "Rn", atomicMass: 222, numOfNeutrons: 136, numOfProtons: 86, numOfElectrons: 86, period: 6, group: 18, phase: "gas", radioactive: true, natural: true, metal: true, nonmetal: nil, metalloid: nil, type: "yes", atomicRadius: 1.3, electronegativity: nil, firstIonization: 10.7485, density: 0.00973, meltingPoint: 202.15, boilingPoint: 211.3, numOfIsotopes: 20, discoverer: "Dorn", Year: 1900, specificHeat: 0.094, NumberofShells: 6, NumberofValence: 8),
    ChemistryElements(atomicNumber: 87, backgroundColor: colorDict["alkaliMetal"]!, elementName: "Francium", symbol: "Fr", atomicMass: 223, numOfNeutrons: 136, numOfProtons: 87, numOfElectrons: 87, period: 7, group: 1, phase: "solid", radioactive: true, natural: true, metal: true, nonmetal: nil, metalloid: nil, type: "yes", atomicRadius: nil, electronegativity: 0.7, firstIonization: 4.0727, density: 1.87, meltingPoint: 300.15, boilingPoint: 950, numOfIsotopes: 21, discoverer: "Perey", Year: 1939, specificHeat: nil, NumberofShells: 7, NumberofValence: 1),
    ChemistryElements(atomicNumber: 88, backgroundColor: colorDict["alkalineEarthMetal"]!, elementName: "Radium", symbol: "Ra", atomicMass: 226, numOfNeutrons: 138, numOfProtons: 88, numOfElectrons: 88, period: 7, group: 2, phase: "solid", radioactive: true, natural: true, metal: true, nonmetal: nil, metalloid: nil, type: "yes", atomicRadius: nil, electronegativity: 0.9, firstIonization: 5.2784, density: 5.5, meltingPoint: 973.15, boilingPoint: 2010, numOfIsotopes: 15, discoverer: "Pierre and Marie Curie", Year: 1898, specificHeat: nil, NumberofShells: 7, NumberofValence: 2),
    ChemistryElements(atomicNumber: 89, backgroundColor: colorDict["actinide"]!, elementName: "Actinium", symbol: "Ac", atomicMass: 227, numOfNeutrons: 138, numOfProtons: 89, numOfElectrons: 89, period: 7, group: 3, phase: "solid", radioactive: true, natural: true, metal: true, nonmetal: nil, metalloid: nil, type: "yes", atomicRadius: nil, electronegativity: 1.1, firstIonization: 5.17, density: 10.1, meltingPoint: 1323.15, boilingPoint: 3471, numOfIsotopes: 11, discoverer: "Debierne/Giesel", Year: 1899, specificHeat: 0.12, NumberofShells: 7, NumberofValence: nil),
    ChemistryElements(atomicNumber: 90, backgroundColor: colorDict["actinide"]!, elementName: "Thorium", symbol: "Th", atomicMass: 232.038, numOfNeutrons: 142, numOfProtons: 90, numOfElectrons: 90, period: 7, group: nil, phase: "solid", radioactive: true, natural: true, metal: true, nonmetal: nil, metalloid: nil, type: "yes", atomicRadius: nil, electronegativity: 1.3, firstIonization: 6.3067, density: 11.7, meltingPoint: 2028.15, boilingPoint: 5061, numOfIsotopes: 12, discoverer: "Berzelius", Year: 1828, specificHeat: 0.113, NumberofShells: 7, NumberofValence: nil),
    ChemistryElements(atomicNumber: 91, backgroundColor: colorDict["actinide"]!, elementName: "Protactinium", symbol: "Pa", atomicMass: 231.036, numOfNeutrons: 140, numOfProtons: 91, numOfElectrons: 91, period: 7, group: nil, phase: "solid", radioactive: true, natural: true, metal: true, nonmetal: nil, metalloid: nil, type: "yes", atomicRadius: nil, electronegativity: 1.5, firstIonization: 5.89, density: 15.4, meltingPoint: 1873.15, boilingPoint: 4300, numOfIsotopes: 14, discoverer: "Hahn and Meitner", Year: 1917, specificHeat: nil, NumberofShells: 7, NumberofValence: nil),
    ChemistryElements(atomicNumber: 92, backgroundColor: colorDict["actinide"]!, elementName: "Uranium", symbol: "U", atomicMass: 238.029, numOfNeutrons: 146, numOfProtons: 92, numOfElectrons: 92, period: 7, group: nil, phase: "solid", radioactive: true, natural: true, metal: true, nonmetal: nil, metalloid: nil, type: "yes", atomicRadius: nil, electronegativity: 1.38, firstIonization: 6.1941, density: 19, meltingPoint: 1405.15, boilingPoint: 4404, numOfIsotopes: 15, discoverer: "Peligot", Year: 1841, specificHeat: 0.116, NumberofShells: 7, NumberofValence: nil),
    ChemistryElements(atomicNumber: 93, backgroundColor: colorDict["actinide"]!, elementName: "Neptunium", symbol: "Np", atomicMass: 237, numOfNeutrons: 144, numOfProtons: 93, numOfElectrons: 93, period: 7, group: nil, phase: "artificial", radioactive: true, natural: nil, metal: true, nonmetal: nil, metalloid: nil, type: nil, atomicRadius: nil, electronegativity: 1.36, firstIonization: 6.2657, density: 20.5, meltingPoint: 913.15, boilingPoint: 4273, numOfIsotopes: 153, discoverer: "McMillan and Abelson", Year: 1940, specificHeat: nil, NumberofShells: 7, NumberofValence: nil),
    ChemistryElements(atomicNumber: 94, backgroundColor: colorDict["actinide"]!, elementName: "Plutonium", symbol: "Pu", atomicMass: 244, numOfNeutrons: 150, numOfProtons: 94, numOfElectrons: 94, period: 7, group: nil, phase: "artificial", radioactive: true, natural: nil, metal: true, nonmetal: nil, metalloid: nil, type: nil, atomicRadius: nil, electronegativity: 1.28, firstIonization: 6.0262, density: 19.8, meltingPoint: 913.15, boilingPoint: 3501, numOfIsotopes: 163, discoverer: "Seaborg et al.", Year: 1940, specificHeat: nil, NumberofShells: 7, NumberofValence: nil),
    ChemistryElements(atomicNumber: 95, backgroundColor: colorDict["actinide"]!, elementName: "Americium", symbol: "Am", atomicMass: 243, numOfNeutrons: 148, numOfProtons: 95, numOfElectrons: 95, period: 7, group: nil, phase: "artificial", radioactive: true, natural: nil, metal: true, nonmetal: nil, metalloid: nil, type: nil, atomicRadius: nil, electronegativity: 1.3, firstIonization: 5.9738, density: 13.7, meltingPoint: 1267.15, boilingPoint: 2880, numOfIsotopes: 133, discoverer: "Seaborg et al.", Year: 1944, specificHeat: nil, NumberofShells: 7, NumberofValence: nil),
    ChemistryElements(atomicNumber: 96, backgroundColor: colorDict["actinide"]!, elementName: "Curium", symbol: "Cm", atomicMass: 247, numOfNeutrons: 151, numOfProtons: 96, numOfElectrons: 96, period: 7, group: nil, phase: "artificial", radioactive: true, natural: nil, metal: true, nonmetal: nil, metalloid: nil, type: nil, atomicRadius: nil, electronegativity: 1.3, firstIonization: 5.9915, density: 13.5, meltingPoint: 1340.15, boilingPoint: 3383, numOfIsotopes: 133, discoverer: "Seaborg et al.", Year: 1944, specificHeat: nil, NumberofShells: 7, NumberofValence: nil),
    ChemistryElements(atomicNumber: 97, backgroundColor: colorDict["actinide"]!, elementName: "Berkelium", symbol: "Bk", atomicMass: 247, numOfNeutrons: 150, numOfProtons: 97, numOfElectrons: 97, period: 7, group: nil, phase: "artificial", radioactive: true, natural: nil, metal: true, nonmetal: nil, metalloid: nil, type: nil, atomicRadius: nil, electronegativity: 1.3, firstIonization: 6.1979, density: 14.8, meltingPoint: 1259.15, boilingPoint: 983, numOfIsotopes: 83, discoverer: "Seaborg et al.", Year: 1949, specificHeat: nil, NumberofShells: 7, NumberofValence: nil),
    ChemistryElements(atomicNumber: 98, backgroundColor: colorDict["actinide"]!, elementName: "Californium", symbol: "Cf", atomicMass: 251, numOfNeutrons: 153, numOfProtons: 98, numOfElectrons: 98, period: 7, group: nil, phase: "artificial", radioactive: true, natural: nil, metal: true, nonmetal: nil, metalloid: nil, type: nil, atomicRadius: nil, electronegativity: 1.3, firstIonization: 6.2817, density: 15.1, meltingPoint: 1925.15, boilingPoint: 1173, numOfIsotopes: 123, discoverer: "Seaborg et al.", Year: 1950, specificHeat: nil, NumberofShells: 7, NumberofValence: nil),
    ChemistryElements(atomicNumber: 99, backgroundColor: colorDict["actinide"]!, elementName: "Einsteinium", symbol: "Es", atomicMass: 252, numOfNeutrons: 153, numOfProtons: 99, numOfElectrons: 99, period: 7, group: nil, phase: "artificial", radioactive: true, natural: nil, metal: true, nonmetal: nil, metalloid: nil, type: nil, atomicRadius: nil, electronegativity: 1.3, firstIonization: 6.42, density: 13.5, meltingPoint: 1133.15, boilingPoint: nil, numOfIsotopes: 123, discoverer: "Ghiorso et al.", Year: 1952, specificHeat: nil, NumberofShells: 7, NumberofValence: nil),
    ChemistryElements(atomicNumber: 100, backgroundColor: colorDict["actinide"]!, elementName: "Fermium", symbol: "Fm", atomicMass: 257, numOfNeutrons: 157, numOfProtons: 100, numOfElectrons: 100, period: 7, group: nil, phase: "artificial", radioactive: true, natural: nil, metal: true, nonmetal: nil, metalloid: nil, type: nil, atomicRadius: nil, electronegativity: 1.3, firstIonization: 6.5, density: nil, meltingPoint: nil, boilingPoint: nil, numOfIsotopes: 103, discoverer: "Ghiorso et al.", Year: 1953, specificHeat: nil, NumberofShells: 7, NumberofValence: nil),
    ChemistryElements(atomicNumber: 101, backgroundColor: colorDict["actinide"]!, elementName: "Mendelevium", symbol: "Md", atomicMass: 258, numOfNeutrons: 157, numOfProtons: 101, numOfElectrons: 101, period: 7, group: nil, phase: "artificial", radioactive: true, natural: nil, metal: true, nonmetal: nil, metalloid: nil, type: nil, atomicRadius: nil, electronegativity: 1.3, firstIonization: 6.58, density: nil, meltingPoint: nil, boilingPoint: nil, numOfIsotopes: 33, discoverer: "Ghiorso et al.", Year: 1955, specificHeat: nil, NumberofShells: 7, NumberofValence: nil),
    ChemistryElements(atomicNumber: 102, backgroundColor: colorDict["actinide"]!, elementName: "Nobelium", symbol: "No", atomicMass: 259, numOfNeutrons: 157, numOfProtons: 102, numOfElectrons: 102, period: 7, group: nil, phase: "artificial", radioactive: true, natural: nil, metal: true, nonmetal: nil, metalloid: nil, type: nil, atomicRadius: nil, electronegativity: 1.3, firstIonization: 6.65, density: nil, meltingPoint: nil, boilingPoint: nil, numOfIsotopes: 73, discoverer: "Ghiorso et al.", Year: 1958, specificHeat: nil, NumberofShells: 7, NumberofValence: nil),
    ChemistryElements(atomicNumber: 103, backgroundColor: colorDict["actinide"]!, elementName: "Lawrencium", symbol: "Lr", atomicMass: 262, numOfNeutrons: 159, numOfProtons: 103, numOfElectrons: 103, period: 7, group: nil, phase: "artificial", radioactive: true, natural: nil, metal: true, nonmetal: nil, metalloid: nil, type: nil, atomicRadius: nil, electronegativity: nil, firstIonization: nil, density: nil, meltingPoint: nil, boilingPoint: nil, numOfIsotopes: 203, discoverer: "Ghiorso et al.", Year: 1961, specificHeat: nil, NumberofShells: 7, NumberofValence: nil),
    ChemistryElements(atomicNumber: 104, backgroundColor: colorDict["transitionMetal"]!, elementName: "Rutherfordium", symbol: "Rf", atomicMass: 261, numOfNeutrons: 157, numOfProtons: 104, numOfElectrons: 104, period: 7, group: 4, phase: "artificial", radioactive: true, natural: nil, metal: true, nonmetal: nil, metalloid: nil, type: nil, atomicRadius: nil, electronegativity: nil, firstIonization: nil, density: 18.1, meltingPoint: nil, boilingPoint: nil, numOfIsotopes: nil, discoverer: "Ghiorso et al.", Year: 1969, specificHeat: nil, NumberofShells: 7, NumberofValence: nil),
    ChemistryElements(atomicNumber: 105, backgroundColor: colorDict["transitionMetal"]!, elementName: "Dubnium", symbol: "Db", atomicMass: 262, numOfNeutrons: 157, numOfProtons: 105, numOfElectrons: 105, period: 7, group: 5, phase: "artificial", radioactive: true, natural: nil, metal: true, nonmetal: nil, metalloid: nil, type: nil, atomicRadius: nil, electronegativity: nil, firstIonization: nil, density: 39, meltingPoint: nil, boilingPoint: nil, numOfIsotopes: nil, discoverer: "Ghiorso et al.", Year: 1970, specificHeat: nil, NumberofShells: 7, NumberofValence: nil),
    ChemistryElements(atomicNumber: 106, backgroundColor: colorDict["transitionMetal"]!, elementName: "Seaborgium", symbol: "Sg", atomicMass: 266, numOfNeutrons: 160, numOfProtons: 106, numOfElectrons: 106, period: 7, group: 6, phase: "artificial", radioactive: true, natural: nil, metal: true, nonmetal: nil, metalloid: nil, type: nil, atomicRadius: nil, electronegativity: nil, firstIonization: nil, density: 35, meltingPoint: nil, boilingPoint: nil, numOfIsotopes: nil, discoverer: "Ghiorso et al.", Year: 1974, specificHeat: nil, NumberofShells: 7, NumberofValence: nil),
    ChemistryElements(atomicNumber: 107, backgroundColor: colorDict["transitionMetal"]!, elementName: "Bohrium", symbol: "Bh", atomicMass: 264, numOfNeutrons: 157, numOfProtons: 107, numOfElectrons: 107, period: 7, group: 7, phase: "artificial", radioactive: true, natural: nil, metal: true, nonmetal: nil, metalloid: nil, type: nil, atomicRadius: nil, electronegativity: nil, firstIonization: nil, density: 37, meltingPoint: nil, boilingPoint: nil, numOfIsotopes: nil, discoverer: "Armbruster and MÔøΩnzenberg", Year: 1981, specificHeat: nil, NumberofShells: 7, NumberofValence: nil),
    ChemistryElements(atomicNumber: 108, backgroundColor: colorDict["transitionMetal"]!, elementName: "Hassium", symbol: "Hs", atomicMass: 267, numOfNeutrons: 159, numOfProtons: 108, numOfElectrons: 108, period: 7, group: 8, phase: "artificial", radioactive: true, natural: nil, metal: true, nonmetal: nil, metalloid: nil, type: nil, atomicRadius: nil, electronegativity: nil, firstIonization: nil, density: 41, meltingPoint: nil, boilingPoint: nil, numOfIsotopes: nil, discoverer: "Armbruster and MÔøΩnzenberg", Year: 1983, specificHeat: nil, NumberofShells: 7, NumberofValence: nil),
    ChemistryElements(atomicNumber: 109, backgroundColor: colorDict["unknownChemicalProperties"]!, elementName: "Meitnerium", symbol: "Mt", atomicMass: 268, numOfNeutrons: 159, numOfProtons: 109, numOfElectrons: 109, period: 7, group: 9, phase: "artificial", radioactive: true, natural: nil, metal: true, nonmetal: nil, metalloid: nil, type: nil, atomicRadius: nil, electronegativity: nil, firstIonization: nil, density: 35, meltingPoint: nil, boilingPoint: nil, numOfIsotopes: nil, discoverer: "GSI, Darmstadt, West Germany", Year: 1982, specificHeat: nil, NumberofShells: 7, NumberofValence: nil),
    ChemistryElements(atomicNumber: 110, backgroundColor: colorDict["unknownChemicalProperties"]!, elementName: "Darmstadtium ", symbol: "Ds ", atomicMass: 271, numOfNeutrons: 161, numOfProtons: 110, numOfElectrons: 110, period: 7, group: 10, phase: "artificial", radioactive: true, natural: nil, metal: true, nonmetal: nil, metalloid: nil, type: nil, atomicRadius: nil, electronegativity: nil, firstIonization: nil, density: nil, meltingPoint: nil, boilingPoint: nil, numOfIsotopes: nil, discoverer: nil, Year: 1994, specificHeat: nil, NumberofShells: 7, NumberofValence: nil),
    ChemistryElements(atomicNumber: 111, backgroundColor: colorDict["unknownChemicalProperties"]!, elementName: "Roentgenium ", symbol: "Rg ", atomicMass: 272, numOfNeutrons: 161, numOfProtons: 111, numOfElectrons: 111, period: 7, group: 11, phase: "artificial", radioactive: true, natural: nil, metal: true, nonmetal: nil, metalloid: nil, type: nil, atomicRadius: nil, electronegativity: nil, firstIonization: nil, density: nil, meltingPoint: nil, boilingPoint: nil, numOfIsotopes: nil, discoverer: nil, Year: 1994, specificHeat: nil, NumberofShells: 7, NumberofValence: nil),
    ChemistryElements(atomicNumber: 112, backgroundColor: colorDict["postTransitionalMetal"]!, elementName: "Copernicium ", symbol: "Cn ", atomicMass: 285, numOfNeutrons: 173, numOfProtons: 112, numOfElectrons: 112, period: 7, group: 12, phase: "artificial", radioactive: true, natural: nil, metal: true, nonmetal: nil, metalloid: nil, type: nil, atomicRadius: nil, electronegativity: nil, firstIonization: nil, density: nil, meltingPoint: nil, boilingPoint: nil, numOfIsotopes: nil, discoverer: nil, Year: 1996, specificHeat: nil, NumberofShells: 7, NumberofValence: nil),
    ChemistryElements(atomicNumber: 113, backgroundColor: colorDict["unknownChemicalProperties"]!, elementName: "Nihonium", symbol: "Nh", atomicMass: 284, numOfNeutrons: 171, numOfProtons: 113, numOfElectrons: 113, period: 7, group: 13, phase: "artificial", radioactive: true, natural: nil, metal: true, nonmetal: nil, metalloid: nil, type: nil, atomicRadius: nil, electronegativity: nil, firstIonization: nil, density: nil, meltingPoint: nil, boilingPoint: nil, numOfIsotopes: nil, discoverer: nil, Year: 2004, specificHeat: nil, NumberofShells: 7, NumberofValence: 3),
    ChemistryElements(atomicNumber: 114, backgroundColor: colorDict["unknownChemicalProperties"]!, elementName: "Flerovium", symbol: "Fl", atomicMass: 289, numOfNeutrons: 175, numOfProtons: 114, numOfElectrons: 114, period: 7, group: 14, phase: "artificial", radioactive: true, natural: nil, metal: true, nonmetal: nil, metalloid: nil, type: nil, atomicRadius: nil, electronegativity: nil, firstIonization: nil, density: nil, meltingPoint: nil, boilingPoint: nil, numOfIsotopes: nil, discoverer: nil, Year: 1999, specificHeat: nil, NumberofShells: 7, NumberofValence: 4),
    ChemistryElements(atomicNumber: 115, backgroundColor: colorDict["unknownChemicalProperties"]!, elementName: "Moscovium", symbol: "Mc", atomicMass: 288, numOfNeutrons: 173, numOfProtons: 115, numOfElectrons: 115, period: 7, group: 15, phase: "artificial", radioactive: true, natural: nil, metal: true, nonmetal: nil, metalloid: nil, type: nil, atomicRadius: nil, electronegativity: nil, firstIonization: nil, density: nil, meltingPoint: nil, boilingPoint: nil, numOfIsotopes: nil, discoverer: nil, Year: 2010, specificHeat: nil, NumberofShells: 7, NumberofValence: 5),
    ChemistryElements(atomicNumber: 116, backgroundColor: colorDict["unknownChemicalProperties"]!, elementName: "Livermorium", symbol: "Lv", atomicMass: 292, numOfNeutrons: 176, numOfProtons: 116, numOfElectrons: 116, period: 7, group: 16, phase: "artificial", radioactive: true, natural: nil, metal: true, nonmetal: nil, metalloid: nil, type: nil, atomicRadius: nil, electronegativity: nil, firstIonization: nil, density: nil, meltingPoint: nil, boilingPoint: nil, numOfIsotopes: nil, discoverer: nil, Year: 2000, specificHeat: nil, NumberofShells: 7, NumberofValence: 6),
    ChemistryElements(atomicNumber: 117, backgroundColor: colorDict["unknownChemicalProperties"]!, elementName: "Tennessine", symbol: "Ts", atomicMass: 295, numOfNeutrons: 178, numOfProtons: 117, numOfElectrons: 117, period: 7, group: 17, phase: "artificial", radioactive: true, natural: nil, metal: nil, nonmetal: true, metalloid: nil, type: nil, atomicRadius: nil, electronegativity: nil, firstIonization: nil, density: nil, meltingPoint: nil, boilingPoint: nil, numOfIsotopes: nil, discoverer: nil, Year: 2010, specificHeat: nil, NumberofShells: 7, NumberofValence: 7),
    ChemistryElements(atomicNumber: 118, backgroundColor: colorDict["unknownChemicalProperties"]!, elementName: "Oganesson", symbol: "Og", atomicMass: 294, numOfNeutrons: 176, numOfProtons: 118, numOfElectrons: 118, period: 7, group: 18, phase: "artificial", radioactive: true, natural: nil, metal: nil, nonmetal: true, metalloid: nil, type: nil, atomicRadius: nil, electronegativity: nil, firstIonization: nil, density: nil, meltingPoint: nil, boilingPoint: nil, numOfIsotopes: nil, discoverer: nil, Year: 2006, specificHeat: nil, NumberofShells: 7, NumberofValence: 8)
]

//let color = UIColor(red: 255/255, green: 102/255, blue: 102/255, alpha: 1.0)
//255, 102, 102
